// <auto-generated />
namespace Fakturisanje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cenaStavke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cenaStavke));
        
        string IMigrationMetadata.Id
        {
            get { return "201907261615351_cenaStavke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
